### ISSUE TITLE
ADServicePrincipalName Need $credential attribute

### ISSUE THREAD

**Issue by Keldandorin** [PowerShell/ActiveDirectoryDsc#239] opened 2019-02-13 14:33 UTC
#### Details of the scenario you tried and the problem that is occurring
Trying to add SPN to service account from server that dont have AD permission

#### Suggested solution to the issue
    add $credential attribute so its possible to add SPN from server client that do not have permission

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
 xADServicePrincipalName MIMService
        {
            ServicePrincipalName = 'http/MIMService'
            Ensure = 'Present'
            Account ='ads-MIMService'
        }
# insert configuration here
```

#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

    Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')
-->
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2007.amd64fre.rs1_release.171231-1800
OsLanguage           : en-US
OsMuiLanguages       : {en-US}


#### Version and build of PowerShell the target node is running
<!--
    To help with this information, please run this command:
    $PSVersionTable
-->

Name                           Value                                                                                                                                                                  
----                           -----                                                                                                                                                                  
PSVersion                      5.1.14393.1944                                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                
BuildVersion                   10.0.14393.1944                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                                    
SerializationVersion           1.1.0.1   
#### Version of the DSC module that was used ('dev' if using current dev branch)
2.23.0.0

**Comment by johlju** [comment] 2019-02-28 06:37
Is it possible for you to use the built-in `PsDscRunAsCredential` which will make the resource run as that user?

**Comment by johlju** [comment] 2019-08-03 09:54
Closing this and assume the issue is resolved, if it is not, then please reopen.

**Closed by johlju** 2019-08-03 09:54 UTC
Labels: needs more information
